server:
  applicationConnectors:
    - type: http
      port: 8181
  adminConnectors:
    - type: http
      port: 8282

swagger:
  resourcePackage: com.businessbook.phonebook

dataSource:
  driverClassName: org.postgresql.Driver
  username: root
  password: 123456
  url: jdbc:postgresql://localhost:5432/phonebook
