server:
  applicationConnectors:
    - type: http
      port: 8181
  adminConnectors:
    - type: http
      port: 8282

swagger:
  resourcePackage: com.businessbook.phonebook

dataSource:
  driverClassName: com.mysql.cj.jdbc.Driver
  username: root
  password: 123456
  url: jdbc:mysql://localhost:3306/phonebook
